++ /apps/intel-2020.2/intel-2020.2/intelpython3/bin/conda shell.bash hook
+ __conda_setup=
+ '[' 127 -eq 0 ']'
+ '[' -f /apps/intel-2020.2/intel-2020.2/intelpython3/etc/profile.d/conda.sh ']'
+ export PATH=/apps/intel-2020.2/intel-2020.2/intelpython3/bin:/apps/contrib/rocoto/1.3.6/bin:/apps/contrib/noaatools/3.1/bin:/usr/sbin:/usr/bin:/apps/sbin:/apps/bin:/opt/slurm/bin
+ PATH=/apps/intel-2020.2/intel-2020.2/intelpython3/bin:/apps/contrib/rocoto/1.3.6/bin:/apps/contrib/noaatools/3.1/bin:/usr/sbin:/usr/bin:/apps/sbin:/apps/bin:/opt/slurm/bin
+ unset __conda_setup
+ module unload python/3.9.2
+ '[' -z '' ']'
+ case "$-" in
+ __lmod_sh_dbg=x
+ '[' -n x ']'
+ set +x
Shell debugging temporarily silenced: export LMOD_SH_DBG_ON=1 for Lmod's output

Note: the module "python/3.9.2" cannot be unloaded because it was not loaded.

Shell debugging restarted
+ unset __lmod_sh_dbg
+ return 0
+ module load miniconda2/4.7.12.1
+ '[' -z '' ']'
+ case "$-" in
+ __lmod_sh_dbg=x
+ '[' -n x ']'
+ set +x
Shell debugging temporarily silenced: export LMOD_SH_DBG_ON=1 for Lmod's output
Shell debugging restarted
+ unset __lmod_sh_dbg
+ return 0
+ conda activate /work2/noaa/da/ytang/py39

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


+ export PYTHONPATH=/work2/noaa/da/ytang/py39/lib/python3.9/site-packages
+ PYTHONPATH=/work2/noaa/da/ytang/py39/lib/python3.9/site-packages
+ export __LMOD_REF_COUNT_PYTHONPATH=/work2/noaa/da/ytang/py39/lib/python3.9/site-packages
+ __LMOD_REF_COUNT_PYTHONPATH=/work2/noaa/da/ytang/py39/lib/python3.9/site-packages
+ export CONDA_PYTHON_EXE=/work2/noaa/da/ytang/py39/bin/python
+ CONDA_PYTHON_EXE=/work2/noaa/da/ytang/py39/bin/python
+ SDATE=20200215
+ EDATE=20200216
+ DATADIR=/work/noaa/gsd-fv3-dev/bhuang/JEDI-FV3/expRuns/MISC/VIIRS-AWS/data/20200215-20200216
+ PYEXE=/work/noaa/gsd-fv3-dev/bhuang/JEDI-FV3/expRuns/MISC/VIIRS-AWS/viirs_aws_download_globalmode_v1_bo.py
+ python /work/noaa/gsd-fv3-dev/bhuang/JEDI-FV3/expRuns/MISC/VIIRS-AWS/viirs_aws_download_globalmode_v1_bo.py 20200215 20200216 /work/noaa/gsd-fv3-dev/bhuang/JEDI-FV3/expRuns/MISC/VIIRS-AWS/data/20200215-20200216
Traceback (most recent call last):
  File "/work/noaa/gsd-fv3-dev/bhuang/JEDI-FV3/expRuns/MISC/VIIRS-AWS/viirs_aws_download_globalmode_v1_bo.py", line 32, in <module>
    import s3fs
  File "/work2/noaa/da/ytang/py39/lib/python3.9/site-packages/s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "/work2/noaa/da/ytang/py39/lib/python3.9/site-packages/s3fs/core.py", line 107
    async def _error_wrapper(func, *, args=(), kwargs=None, retries):
            ^
SyntaxError: invalid syntax
+ exit 0
